### ISSUE TITLE
Provide action to add buffer to list without toggling/improve mapping configuration

### ISSUE THREAD

**Issue by jemag** [otavioschwanck/arrow.nvim#11]
Currently the `s` key toggles between adding and removing items from the list. The issue is that I often want to quickly add a bunch of different files without checking if they are already there and I end up removing them.

I see that the `save` https://github.com/otavioschwanck/arrow.nvim/blob/75c892c441cbd51b3b5bc4c527455801e0a7c174/lua/arrow/persist.lua#L41 function already exists. However:
1. is it safe to use that exposed function?
2. it would be nice to provide an 'on_attach' function where we can set local bindings to the arrow buffer instead of global ones

**Comment by otavioschwanck** [comment]
> Currently the `s` key toggles between adding and removing items from the list. The issue is that I often want to quickly add a bunch of different files without checking if they are already there and I end up removing them.
> 
> I see that the `save`
> 
> https://github.com/otavioschwanck/arrow.nvim/blob/75c892c441cbd51b3b5bc4c527455801e0a7c174/lua/arrow/persist.lua#L41
> 
> function already exists. However:
> 1. is it safe to use that exposed function?
> 2. it would be nice to provide an 'on_attach' function where we can set local bindings to the arrow buffer instead of global ones

You can use safely: 

```lua
vim.keymap.set("n", "<C-s>", require("arrow.persist").toggle)
```

**Comment by jemag** [comment]
Is there a way to set the keybind only for the `arrow` buffer though?

Basically I am trying to do either something like:
```lua
require("arrow").setup({
  on_attach = function()
	vim.keymap.set("n", "a", require("arrow.persist").save, { buffer = true})
  end,
})
```
or maybe
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "arrow",
  callback = function()
    vim.keymap.set("n", "a", require("arrow.persist").save, { buffer = true})
  end,
})
```

**Comment by otavioschwanck** [comment]
> Is there a way to set the keybind only for the `arrow` buffer though?
> 
> Basically I am trying to do either something like:
> 
> ```lua
> require("arrow").setup({
>   on_attach = function()
> 	vim.keymap.set("n", "a", require("arrow.persist").save, { buffer = true})
>   end,
> })
> ```
> 
> or maybe
> 
> ```lua
> vim.api.nvim_create_autocmd("FileType", {
>   pattern = "arrow",
>   callback = function()
>     vim.keymap.set("n", "a", require("arrow.persist").save, { buffer = true})
>   end,
> })
> ```

There is no way to just save, just toggle.  I will add an option to do that later on the day

**Comment by otavioschwanck** [comment]
Created an option to save / remove without toggle:

https://github.com/otavioschwanck/arrow.nvim/commit/a302cebc0e52b2e7f5d2cb09066fcf839176dd06

Just add to setup:

`separate_save_and_remove = true,`
