### ISSUE TITLE
No support for directories?

### ISSUE THREAD

**Issue by mblarsen** [otavioschwanck/arrow.nvim#12]
Expected behavior 

```
api . modules
api . development/eu-central-1
api . production/eu-central-1
```

Actual behavior

```
. modules/api
. development/eu-central-1/api
. production/eu-central-1/api
```

I'm guessing the name that matches is no name and then it puts the paths as qualifier for that.

Aside from the rendering issue it works fine with directories. (in my case paired with oil.nvim)

<img width="479" alt="image" src="https://github.com/otavioschwanck/arrow.nvim/assets/247048/6953556f-80fc-4ea8-bce1-4ea52444042b">

**Comment by otavioschwanck** [comment]
> Expected behavior
> 
> ```
> api . modules
> api . development/eu-central-1
> api . production/eu-central-1
> ```
> 
> Actual behavior
> 
> ```
> . modules/api
> . development/eu-central-1/api
> . production/eu-central-1/api
> ```
> 
> I'm guessing the name that matches is no name and then it puts the paths as qualifier for that.
> 
> Aside from the rendering issue it works fine with directories. (in my case paired with oil.nvim)
> 
> <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/247048/303209664-6953556f-80fc-4ea8-bce1-4ea52444042b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDY1NDMsIm5iZiI6MTcwNzQwNjI0MywicGF0aCI6Ii8yNDcwNDgvMzAzMjA5NjY0LTY5NTM1NTZmLTgwZmMtNGVhOC1iY2UxLTRlYTUyNDQ0MDQyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxNTMwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODc2YTFmNmQyYTZiZDkwM2RkMWFlZGQ3OWVjMjU2YmE5OGFkZmJhMjRjYWRmM2I2YTBmZWE4MDM2ZWY0OTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.URtue1nYG4FQ4zSuEQ53qwkII5pEzvTp5g8U78lFiyw">

i will add the support for directories later in the week

**Comment by otavioschwanck** [comment]
Done at https://github.com/otavioschwanck/arrow.nvim/commit/2bfe485b483ac2aaefe91fb1ab793e13918f13e0

![image](https://github.com/otavioschwanck/arrow.nvim/assets/9551316/657fbcfa-67a7-4566-bf27-4052015d3e8a)

**Comment by mblarsen** [comment]
That was fast :D

Any reason why not applying the same "duplicate" name logic as for files? I.e. when two directory names are the same show `. parent/path`. 

```
api . modules
api . development/eu-central-1
api . production/eu-central-1
```

<img width="404" alt="image" src="https://github.com/otavioschwanck/arrow.nvim/assets/247048/e43be9ff-45e3-4206-8c68-060757bb3e67">

**Comment by otavioschwanck** [comment]
> That was fast :D
> 
> Any reason why not applying the same "duplicate" name logic as for files? I.e. when two directory names are the same show `. parent/path`.
> 
> ```
> api . modules
> api . development/eu-central-1
> api . production/eu-central-1
> ```
> 
> <img alt="image" width="404" src="https://private-user-images.githubusercontent.com/247048/303632337-e43be9ff-45e3-4206-8c68-060757bb3e67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODEyMTgsIm5iZiI6MTcwNzQ4MDkxOCwicGF0aCI6Ii8yNDcwNDgvMzAzNjMyMzM3LWU0M2JlOWZmLTQ1ZTMtNDIwNi04YzY4LTA2MDc1N2JiM2U2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjE1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjA3MThjZDNlNjk4Mzc1MWRjOTVjYWRlOTVlYzhmYzNlNDJhZDM3N2UxYTRlNjAzOWQ2ZGVkNzQzZDBiMmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pMaerKFEk9o7-nNungXuiUAG2-3w9jSuvQARDc17uGk">

you think that logic makes sense? i will do it

**Comment by otavioschwanck** [comment]
Done:

![image](https://github.com/otavioschwanck/arrow.nvim/assets/9551316/aa45420f-414a-4648-b486-1db2b558154d)

**Comment by mblarsen** [comment]
Really nice, thanks a lot <3
