### ISSUE TITLE
Handbook hint cut off

### ISSUE THREAD

**Issue by sschleemilch** [otavioschwanck/arrow.nvim#17]
First of all: Loving the plugin and it replaced harpoon for me <3.

I just noticed that the handbook hint is cut off for my setup.
Wanted to ask whether it is something I have in my setup or whether this could be a known problem:
![image](https://github.com/otavioschwanck/arrow.nvim/assets/12069137/9f522f4c-5ec9-4603-8a5b-96e1146e7d32)

Config is pretty default:
```lua
{
  "otavioschwanck/arrow.nvim",
  opts = {
    show_icons = true,
    leader_key = ";",
  },
},
```

Using most recent master:
`"arrow.nvim": { "branch": "master", "commit": "79527117368995b81aa1a77714b49d0d7535274b" },`

**Comment by sschleemilch** [comment]
Just found out that it is fixed by disabling https://github.com/stevearc/dressing.nvim for me.

**Comment by sschleemilch** [comment]
Or not... Tried the same thing on my other  machine and issue is there also without dressing.

**Comment by otavioschwanck** [comment]
> Or not... Tried the same thing on my other machine and issue is there also without dressing.

could you try with a different font?

**Comment by 231tr0n** [comment]
This issue is reproducible for me as well. Does anyone know any workaround on how to fix this.

**Comment by otavioschwanck** [comment]
> This issue is reproducible for me as well using dressing.nvim. Does anyone know any workaround on how to fix this.

what font and terminal are you using?

**Comment by otavioschwanck** [comment]
i've send a fix to increase the width, could you check ? @sschleemilch

**Comment by 231tr0n** [comment]
> > This issue is reproducible for me as well using dressing.nvim. Does anyone know any workaround on how to fix this.
> 
> what font and terminal are you using?

I am using a nerd font called hurmit. Not mono type

**Comment by otavioschwanck** [comment]
> > > This issue is reproducible for me as well using dressing.nvim. Does anyone know any workaround on how to fix this.
> > 
> > 
> > what font and terminal are you using?
> 
> I am using a nerd font called hurmit. Not mono type

could you try the last fix?
