### ISSUE TITLE
The `separate_by_branch = true` option does not separate

### ISSUE THREAD

**Issue by sQVe** [otavioschwanck/arrow.nvim#20]
Hey, 👋

_Most importantly, thank you for you an excellent plugin! ❤️_ 

I'm trying to separate my bookmarks between branches, and having troubles getting it to work. Setting the `separate_by_branch` option to either `false` or `true` does nothing.

🍻

**Comment by sbyang** [comment]
Good plugin, but same issue.

**Comment by otavioschwanck** [comment]
> Hey, 👋
> 
> _Most importantly, thank you for you an excellent plugin! ❤️_
> 
> I'm trying to separate my bookmarks between branches, and having troubles getting it to work. Setting the `separate_by_branch` option to either `false` or `true` does nothing.
> 
> 🍻

1. how did you setup arrow? 

2. could you try to run inside a project in neovim:

`:lua = require("arrow.git").get_git_branch()` and see if is returning the right branch.

Observation: if you are using some session manager, it can mess arrow.  Check: 

https://github.com/otavioschwanck/arrow.nvim?tab=readme-ov-file#working-with-sessions-plugins

**Comment by cbochs** [comment]
@otavioschwanck I'm guessing the issue _may_ be due to [this line](https://github.com/otavioschwanck/arrow.nvim/blob/master/lua/arrow/git.lua#L5). It assumes the user's current directory has a `.git` subdirectory. However, navigating into any subdirectories of a repo will cause that check to fail. It may be better to use [`:h vim.fs.find`](https://neovim.io/doc/user/lua.html#vim.fs.find()) to search for `.git` instead. This is what [grapple.nvim does](https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/settings.lua#L91).

**Comment by otavioschwanck** [comment]
> @otavioschwanck I'm guessing the issue _may_ be due to [this line](https://github.com/otavioschwanck/arrow.nvim/blob/master/lua/arrow/git.lua#L5). It assumes the user's current directory has a `.git` subdirectory. However, navigating into any subdirectories of a repo will cause that check to fail. It may be better to use [`:h vim.fs.find`](https://neovim.io/doc/user/lua.html#vim.fs.find()) to search for `.git` instead. This is what [grapple.nvim does](https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/settings.lua#L91).

done: https://github.com/otavioschwanck/arrow.nvim/commit/efad6908abe10d7d74b24c203ad62e51662522a2

@sQVe could you test it?

**Comment by sQVe** [comment]
@otavioschwanck It seems to work consistently now.

The issue was a bit weird before - something it worked, and sometimes not. Seems like it should be related to the issue mentioned by @cbochs.

**Comment by sbyang** [comment]
Wow, that was quick.  It works well now.  Thank you!
