### ISSUE TITLE
Failed to navigate to files starting with special char

### ISSUE THREAD

**Issue by matanamidor** [otavioschwanck/arrow.nvim#28]
I am using tanstack router and file routing (also being use in Remix) and when I save a file starting with $RouteName.tsx (Dynamic router) - and when I try to navigate back I get an empty buffer

**Comment by otavioschwanck** [comment]
Fixed: https://github.com/otavioschwanck/arrow.nvim/commit/7e74ae3224a2a224d1bf539623fa0f073fecbe90
