### ISSUE TITLE
FR: Add option to hide the cheatsheet

### ISSUE THREAD

**Issue by chrisgrieser** [otavioschwanck/arrow.nvim#3]
Could there be an option to hide these?

![Pasted image 2024-01-04 at 12 25 55@2x](https://github.com/otavioschwanck/arrow.nvim/assets/73286100/5a73a99f-8d57-4fce-a585-5dbfe0b386fa)

**Comment by otavioschwanck** [comment]
done: https://github.com/otavioschwanck/arrow.nvim/commit/ce7d9027609184431556bfc8ef04a91be6c5dcd0

just add hide_handbook = true on the setup
