### ISSUE TITLE
Feat: allow mapping `next` in the ui

### ISSUE THREAD

**Issue by aarondill** [otavioschwanck/arrow.nvim#31]
I'd like to map `'` to `next` from within the UI (so `;'` goes to the next file), but this doesn't seem to be possible from the current implementation.

**Comment by otavioschwanck** [comment]
https://github.com/otavioschwanck/arrow.nvim/commit/10d1718b0eb1bb7a513848fd68061c06682224a1

Done here.

By default, the mappings for next and prev is ] and [.

You can set it on setup (see the README)
