### ISSUE TITLE
Possible performance issue?

### ISSUE THREAD

**Issue by goingtosleep** [otavioschwanck/arrow.nvim#34]
I noticed a gradual slowdown when changing buffers over time while using `arrow.nvim`. Although I haven't thoroughly investigated the issue, a quick workaround of commenting out [these lines](https://github.com/otavioschwanck/arrow.nvim/blob/master/lua/arrow/init.lua#L156-L164) seems to alleviate the problem. Could you please take a look?

### Steps to reproduce

- Save some bookmarks using `arrow.nvim`.
- Open a session with multiple buffers.
- Use `arrow.nvim` to navigate very quickly between buffers. For example, I have set `leader_key='r'`, rapidly spam something like the following sequence: `r1r1r1r2r2r2r2r3r3r3r3r3r1r1r1r1`.
- Change to a different buffer. The buffer change becomes noticeably slower compared to when started. The slowdown becomes more apparent as you continue to navigate and change.

Please let me know if you need any further information or clarification to investigate this issue. Thanks!

**Comment by otavioschwanck** [comment]
> I noticed a gradual slowdown when changing buffers over time while using `arrow.nvim`. Although I haven't thoroughly investigated the issue, a quick workaround of commenting out [these lines](https://github.com/otavioschwanck/arrow.nvim/blob/master/lua/arrow/init.lua#L156-L164) seems to alleviate the problem. Could you please take a look?
> 
> ### Steps to reproduce
> * Save some bookmarks using `arrow.nvim`.
> * Open a session with multiple buffers.
> * Use `arrow.nvim` to navigate very quickly between buffers. For example, I have set `leader_key='r'`, rapidly spam something like the following sequence: `r1r1r1r2r2r2r2r3r3r3r3r3r1r1r1r1`.
> * Change to a different buffer. The buffer change becomes noticeably slower compared to when started. The slowdown becomes more apparent as you continue to navigate and change.
> 
> Please let me know if you need any further information or clarification to investigate this issue. Thanks!

Thanks for bringing it, i will investigate. 

Those lines is only triggered when the session is changed or directory is changed, commenting those lines should not alleviate the problem.

**Comment by goingtosleep** [comment]
Thanks @otavioschwanck, I'll check and try to make a minimal setup to reproduce. I have many plugins so maybe there is something that triggers the events 🤔

**Comment by otavioschwanck** [comment]
> Thanks @otavioschwanck, I'll check and try to make a minimal setup to reproduce. I have many plugins so maybe there is something that triggers the events 🤔

either way, the session change should not slow down neovim, so, i will fix that later in the week

**Comment by goingtosleep** [comment]
Okay I found the culprit, that's one of my autocmd for `mkview` with `BufLeave` event, and has nothing to do with `arrow.nvim`. Thanks @otavioschwanck for the support, your plugin is very helpful for my workflow.

**Comment by xzbdmw** [comment]
> Okay I found the culprit, that's one of my autocmd for `mkview` with `BufLeave` event, and has nothing to do with `arrow.nvim`. Thanks @otavioschwanck for the support, your plugin is very helpful for my workflow.

Is mkview slow? I also use that autocmd and buffer loading time seems to differ slightly each time.

**Comment by goingtosleep** [comment]
> > Okay I found the culprit, that's one of my autocmd for `mkview` with `BufLeave` event, and has nothing to do with `arrow.nvim`. Thanks @otavioschwanck for the support, your plugin is very helpful for my workflow.
> 
> Is mkview slow? I also use that autocmd and buffer loading time seems to differ slightly each time.

I'm not sure, my autocmd is like this:

```lua
autocmd(
  {'BufLeave', 'QuitPre'},
  'silent! mkview!',
)
```

If `silent!` is removed, it throws an error every time I leave the `arrow.nvim` floating window. Maybe that caused the slowdown.
