### ISSUE TITLE
FR: make *full* path to data files customizable (e.g. for syncing purposes)

### ISSUE THREAD

**Issue by chrisgrieser** [otavioschwanck/arrow.nvim#4]
As far as I can tell, the data files are always saved [in the cache folder](https://github.com/otavioschwanck/arrow.nvim/blob/master/lua/arrow/persist.lua#L11)? I'd suggest making the full path customizable, i.e. adding a setting `data_folder` in addition to `save_key`.

The reason being, that when you work on more than one machines, being able to set a folder would allow you to put the file into your dotfiles repo or a cloud drive for syncing purposes.

**Comment by otavioschwanck** [comment]
On it

**Comment by otavioschwanck** [comment]
Done: https://github.com/otavioschwanck/arrow.nvim/commit/bba131afe67e8d5e77e60a194bb0fa5ce77f94d6

Just add a function on save_path, like:

  save_path = function()
    return vim.fn.stdpath("cache") .. "/arrow" -- never put / at the end.
  end,
  
  Also i found o bug that was not saving inside nvim on cache, fixed too.

**Comment by chrisgrieser** [comment]
fantastic, thank you! Also thanks for the quick implementation

**Comment by chrisgrieser** [comment]
>  -- never put / at the end.

That screams for a fix :P `save_path = save_path:gsub("/$", "")`

**Comment by otavioschwanck** [comment]
> > -- never put / at the end.
> 
> That screams for a fix :P `save_path = save_path:gsub("/$", "")`

i will do it
