### ISSUE TITLE
Bug: icon highlights apply to actions after deleting a few items from the modal

### ISSUE THREAD

**Issue by Gelio** [otavioschwanck/arrow.nvim#44]
Thanks for this great plugin!

I just noticed that when icons are enabled, in the arrow modal, highlights accidentally apply to action hints after you remove a few items.

## Steps to reproduce

1. Add 3 files
2. Go into delete mode (`d`)
3. Remove 2 files

https://github.com/otavioschwanck/arrow.nvim/assets/889383/3e7a88fe-c5e1-4fa4-8dd1-d9d774fce3ef

Notice that the `Remove Current File` action description has `Rem` highlighted in red, which was the highlight used to highlight the `package-lock.json` file.

**Comment by xzbdmw** [comment]
In fact there are two bugs, ArrowCurrentFile will not refresh position during deletion.
