### ISSUE TITLE
Bug: Does not work when changing project during a session

### ISSUE THREAD

**Issue by chrisgrieser** [otavioschwanck/arrow.nvim#5]
When I start neovim in `directory-a`, and then change project (`cd directory-b`), then arrow still shows me the bookmarks from `directory-a`. If I quit and start in `directory-b`, arrow correctly shows me the bookmarks from `directory-b`. 

It seems the bookmark-loading only happens one during initialization and does not monitor changes in the directory. 

I think this could be fixed by triggering bookmark-loading via the [DirChanged event](https://neovim.io/doc/user/autocmd.html#DirChanged).

**Comment by otavioschwanck** [comment]
> When I start neovim in `directory-a`, and then change project (`cd directory-b`), then arrow still shows me the bookmarks from `directory-a`. If I quit and start in `directory-b`, arrow correctly shows me the bookmarks from `directory-b`.
> 
> It seems the bookmark-loading only happens one during initialization and does not monitor changes in the directory.
> 
> I think this could be fixed by triggering bookmark-loading via the [DirChanged event](https://neovim.io/doc/user/autocmd.html#DirChanged).

i will fix it, thanks for bringing it

**Comment by otavioschwanck** [comment]
Done at: https://github.com/otavioschwanck/arrow.nvim/commit/df0210c87229edd4f8e1ed10aa6cd611e4f6cf4b

**Comment by chrisgrieser** [comment]
thanks!
