### ISSUE TITLE
Getting empty buffer only when selecting bookmarks by index key

### ISSUE THREAD

**Issue by Zexius** [otavioschwanck/arrow.nvim#54]
I installed arrow via the default installation via lazy but I am getting a rather weird bug. When loading a saved bookmark via the index key, the buffer appears blank even though the filename is correct on the status line. However if I were use "[" or "]" to cycle to the bookmark it shows up perfectly fine. Any idea what might be causing this?

below is the exact same book mark, the first one access via the index key and the latter accessed via next item
![image](https://github.com/otavioschwanck/arrow.nvim/assets/10585100/51163294-da93-4692-8a4b-08ee1dfd7288)

![image](https://github.com/otavioschwanck/arrow.nvim/assets/10585100/0fb4afa5-1307-47db-b463-3da70b3b4d17)

**Comment by otavioschwanck** [comment]
i will take a look later in the week, thanks from bringing it

**Comment by q-zhengxuanchoy** [comment]
@otavioschwanck just tried it out on my machine, works beautifully. thanks for being so quick on the fix!

**Comment by Zexius** [comment]
@otavioschwanck just tried it out and it works beautifully. Thanks for being so quick on the fix!
