### ISSUE TITLE
[Bug] init failing because default buffer config missing z-index

### ISSUE THREAD

**Issue by ysirobs** [otavioschwanck/arrow.nvim#57]
init.lua is failing on line 100 if you don't have options set for per_buffer_config.zindex. The default value of 50 should be set in https://github.com/otavioschwanck/arrow.nvim/blob/f4aa623528efa906f5e7f68a28d93a82132e331b/lua/arrow/init.lua#L22

**Comment by xzbdmw** [comment]
Hmm, I test without zindex and no error
