### ISSUE TITLE
selectively or completely hide keymaps on the menu

### ISSUE THREAD

**Issue by niamleeson** [otavioschwanck/arrow.nvim#60]
Thank you for this amazing plugin! 

I'd like to hide all or some of the keymaps shown on the menu. Like if I don't include a keymap in the mappings, I don't want it to show up.

**Comment by otavioschwanck** [comment]
> Thank you for this amazing plugin!
> 
> I'd like to hide all or some of the keymaps shown on the menu. Like if I don't include a keymap in the mappings, I don't want it to show up.

Thanks!

You can set the `hide_handbook = true` on the setup.
