### ISSUE TITLE
select item with letter keys as opposed to number keys

### ISSUE THREAD

**Issue by chuan2984** [otavioschwanck/arrow.nvim#62]
really like the plugin so far, is there a way to change the binding for selecting the changed items? like  i would want to use keys on the home-row instead of number keys.

Thanks!

**Comment by AlgusDark** [comment]
It is possible to do this with the following option:
```
index_keys = "123456789zxcbnmZXVBNM,afghjklAFGHJKLwrtyuiopWRTYUIOP",
```

For example, you can do the following for the home row:
```
index_keys = "asdfjkl;"
```

**Comment by chuan2984** [comment]
> It is possible to do this with the following option:
> 
> ```
> index_keys = "123456789zxcbnmZXVBNM,afghjklAFGHJKLwrtyuiopWRTYUIOP",
> ```
> 
> For example, you can do the following for the home row:
> 
> ```
> index_keys = "asdfjkl;"
> ```

thank you!
