### ISSUE TITLE
prev_buffer_bookmark implementation is incorrect

### ISSUE THREAD

**Issue by cprusprus** [otavioschwanck/arrow.nvim#63]
Set 3 marks. Now bind the following:

  require("arrow.commands").commands.next_buffer_bookmark()
and
  require("arrow.commands").commands.prev_buffer_bookmark()

Execute the keybind for next until you're at the 3rd mark. Now execute the prev keybind. You'll see it jumps to mark 1 instead of mark 2.

The fix is to change buffer_ui.prev_item to use:
```
	local sorted_by_line_bookmarks = vim.fn.sort(bookmarks, function(a, b)
		return b.line - a.line
	end)
```

See the examples provided in the sort() docs:
https://neovim.io/doc/user/builtin.html#sort()

(next_item sort func is also incorrect but just happens to work)

**Comment by cprusprus** [comment]
Note the wrapping logic for prev_item is also incorrect. It should be "	go_to_bookmark(sorted_by_line_bookmarks[1])" instead of "	go_to_bookmark(sorted_by_line_bookmarks[#sorted_by_line_bookmarks])" since the list is reverse sorted.

**Comment by otavioschwanck** [comment]
Fixed
