### ISSUE TITLE
FR: add option for global bookmarks

### ISSUE THREAD

**Issue by WildRage1369** [otavioschwanck/arrow.nvim#7]
Adding an option to make all bookmarks global or make specific bookmarks global would be really useful as I tend to work in multiple multiple directories.

**Comment by otavioschwanck** [comment]
Done at: https://github.com/otavioschwanck/arrow.nvim/commit/529ec8246ea9bea759be42626d656f5a06d28a41

Just add global_bookmarks=true on setup
