### ISSUE TITLE
feature request: git branch scoped marks

### ISSUE THREAD

**Issue by nikbrunner** [otavioschwanck/arrow.nvim#8]
Harpoon has a similar option, that the marks are scoped to the current git branch. I love this feature personally. Would it be possible to bring this to this great little plugin? Otherwise I love `arrow.nvim`. 😊

**Comment by otavioschwanck** [comment]
Done at: https://github.com/otavioschwanck/arrow.nvim/commit/f9058e5cf9433258f944518e3980f27c07b4f6c3

just add separate_by_branch=true on the setup

**Comment by nikbrunner** [comment]
I love you! Thats awesome. Thank you! 😊
